version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: projetodb
    restart: always
    environment:
      POSTGRES_DB: projetodb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - projetodb-data:/var/lib/postgresql/data

volumes:
  projetodb-data:
